### ISSUE TITLE
Crash when using dagger

### ISSUE THREAD

**Issue by WolfieWaffle** [the-realest-stu/Adventurers-Toolbox#12]
I cloned this repository yesterday, and when I attacked a cow with a dagger, it gave me this crash report:

https://pastebin.com/3TGPVsJV

I don't know if this is something I did, but the crash report doesn't look like that so it might be something else.

**Comment by the-realest-stu** [comment]
I'm unable to replicate this.

**Comment by WolfieWaffle** [comment]
I will get the latest changes into my local repo/workspace and see if that fixes it

**Comment by WolfieWaffle** [comment]
On second thought it looks like my repo is up to date, but on the discord you said you had some changes? Are these on this github?

**Comment by WolfieWaffle** [comment]
Note I am not using the CurseForge version but this repository cloned, try using that instead.

**Comment by WolfieWaffle** [comment]
No longer happens in newest version.
