### ISSUE TITLE
[1.12.2 v0.2.2 (forge14.23.1.2582)] Mace doesn't do shown damage and have shorter range.

### ISSUE THREAD

**Issue by VallenFrostweaver** [the-realest-stu/Adventurers-Toolbox#13]
When using a mace it does very minimal damage. For example, using a stone mace head plus 2 sticks it makes a mace that states it does 10.5 attack damage (or about 5.25 hearts of damage). Upon using this mace on a cow with 5 hearts it would normally die from that damage. Instead, it does 4 attack damage (or about 2 hearts) and it won't injure entities that are outside of dagger range. I feel it may have had it's stats changed to that of a dagger behind the scenes here.

**Comment by the-realest-stu** [comment]
The range thing sounds like a bug, but the damage is working properly. Maces only do full damage against armored foes.

**Comment by VallenFrostweaver** [comment]
Hm. I was having difficulty testing that. Tried on an iron golem and noticed no difference. Is it more damage with more armor?

**Comment by the-realest-stu** [comment]
Yeah, the damage scales as armor increases.

**Comment by the-realest-stu** [comment]
Fixed the shorter range and completely changed how maces work in a recent update, so they should now do the amount of damage shown in their tooltip.
