### ISSUE TITLE
[Suggestion] Better Better with Mods compat

### ISSUE THREAD

**Issue by build2stone** [the-realest-stu/Adventurers-Toolbox#14]
It would be nice if tools with soulforged steel parts could only be enchanted in the infernal enchanter, for consistency with Better with Mods.

EDIT: I thought Adventurers Toolbox tools couldn't be enchanted in the infernal enchanter, turns out I was just using it wrong.

**Comment by WolfieWaffle** [comment]
Heh I forgot to close this issue, I made a commit that makes it so they won't be enchant-able in the vanilla table if that option is enabled in BWM, fixing this issue.
