### ISSUE TITLE
Pickaxe destroys Hardened Clay

### ISSUE THREAD

**Issue by ulkunderscore** [the-realest-stu/Adventurers-Toolbox#2]
Mining Hardened Clay with Pickaxes doesn't drop the item.
The same goes for Slate from earthworks.

Edit: Redstone Blocks, too.

**Comment by joegman** [comment]
And tinkers' smeltery blocks

**Comment by the-realest-stu** [comment]
That's quite odd. I'll look into this for the next version.

**Comment by elloellie** [comment]
@the-realest-stu I experience the same problem with the stones added by Quark (Limestone/Marble), blocks chiseled by Chisel. The WAILA Harvestability add-on says <ERROR> instead of a red X or green Check, too.

**Comment by rosareven** [comment]
Bone blocks also get destroyed. Normal Minecraft pickaxe can collect them.
