### ISSUE TITLE
Latest Better with Mods versions break HCEnchanting Compat with NoSuchMethod Error, causes JEI to fail to register vanilla recipes

### ISSUE THREAD

**Issue by JHallman** [the-realest-stu/Adventurers-Toolbox#24]
Using the latest versions of Adventurers Toolbox (0.2.9) and Better with Mods (1.12-2.1.15) causes an error with the BwM compat, which result in JEI failing to load the vanilla plugin.

Better with mods recently updated the HCEnchanting module to use EnumEnchantmentType and changed the canEnchantSteel() method.  I'm guessing you'd need to update the various tools in your mod to reference the new method.

Relevant Commits
https://github.com/BetterWithMods/BetterWithMods/commit/9875275f232c6eb0ad9759fa4a1554c5e6061ba9#diff-f5fb003d2e6f20d09ec5eda7a5e8bcef

https://github.com/the-realest-stu/Adventurers-Toolbox/commit/508ce95c63fa99b2e2db0d0ee806316c6fe429fb

Versions
MC: 1.12.2
Forge: 14.23.3.2678
Adventurer's Toolbox: 0.2.9
Better with Mods: 1.12-2.1.15

**Comment by Lordician** [comment]
I can confirm this. After doing some digging this is easily fixed by putting the enchantment as a parameter at the canEnchantSteel method.

**Comment by the-realest-stu** [comment]
Fixed in 0.2.10
