### ISSUE TITLE
Crash that is possibly connected to newer builds of TC

### ISSUE THREAD

**Issue by Sunconure11** [the-realest-stu/Adventurers-Toolbox#35]
https://paste.dimdev.org/yipiyafeju.mccrash

**Comment by WolfieWaffle** [comment]
Unfortunately version compatibility and all that is not really something I'm good at, but this looks like to me that Thaumcraft no longer has a `ResearchStage.getCraft()` method and that is causing the issue. I assume it just needs to be renamed to the new method name.
