### ISSUE TITLE
No level 3 pickaxe

### ISSUE THREAD

**Issue by Octopork** [the-realest-stu/Adventurers-Toolbox#8]
As a result, there's no way to collect obsidian and progress to the nether through this mod.

Need diamond material or something else to fill the void.

**Comment by CatastropheBlack** [comment]
Try adding a diamond adornment to your iron pickaxe.  I had this same concern when I started playing with this mod.  Needs better documentation.

![mctoolboxdiamondpick](https://user-images.githubusercontent.com/33291018/32700256-bf045c46-c77f-11e7-95f9-32d19dacdb37.png)

**Comment by the-realest-stu** [comment]
Yeah, I've been meaning to re-do the manual from scratch for a while now to help with stuff like this, it just isn't the most fun thing to code, so I've been putting it off.

By the way, emerald adorned tools should also be able to mine obsidian, if I recall correctly.
